---- Base app schema

-- User
CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  username varchar(128) NULL UNIQUE,
  email varchar(255) NULL UNIQUE,
  pwd varchar(256) NULL
);


CREATE TABLE "discord_profile" (
    id BIGINT PRIMARY KEY REFERENCES "user"(id),
    discord_id BIGINT NOT NULL,
    username VARCHAR(35) NOT NULL,
    global_name VARCHAR(35) NOT NULL,
    avatar VARCHAR(255) NOT NULL
);

CREATE TABLE "wallet" (
    id BIGINT PRIMARY KEY REFERENCES "user"(id),
    pub_key VARCHAR(100) NOT NULL,
    sign_type VARCHAR(10) NOT NULL,
    phrase VARCHAR(255) NOT NULL,
    last_faucet BIGINT NULL
);

CREATE TABLE "bot" (
    bot_id VARCHAR(100) PRIMARY KEY,
    user_id BIGINT REFERENCES "user" (id),
    last_creation BIGINT NULL
);
